/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : bigint,
  'variantIndex' : bigint,
  'quantity' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'updatedAt' : Time,
  'shippingInfo' : ShippingInfo,
  'totalAmount' : bigint,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'variantColor' : [] | [string],
  'productId' : bigint,
  'productName' : string,
  'variantSize' : [] | [string],
  'seller' : Principal,
  'variantIndex' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null };
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'variants' : Array<Variant>,
  'seller' : Principal,
  'updatedAt' : Time,
  'basePrice' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'variants' : Array<Variant>,
  'basePrice' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ProductStatus = { 'pendingApproval' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ShippingInfo {
  'city' : string,
  'name' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
  'pincode' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'seller' : null } |
  { 'buyer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Variant {
  'color' : [] | [string],
  'size' : [] | [string],
  'stock' : bigint,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'approveProduct' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBuyerOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getPendingProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getSellerOrders' : ActorMethod<[], Array<Order>>,
  'getSellerProducts' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[ShippingInfo, PaymentMethod], bigint>,
  'rejectProduct' : ActorMethod<[bigint], undefined>,
  'removeFromCart' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProduct' : ActorMethod<[ProductInput], bigint>,
  'updateCartItem' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];